spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR}
        namespace: ${NACOS_NAMESPACE:hannote}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
  cassandra:
    keyspace-name: ${CASSANDRA_KEYSPACE:hannote}
    contact-points: ${CASSANDRA_HOST}
    port: ${CASSANDRA_PORT:9042}
    local-datacenter: ${CASSANDRA_DATACENTER:datacenter1}
    schema-action: none

rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER}
  consumer:
    group: hannote_group
    pull-batch-size: 5
