brokerClusterName=HannoteLocalCluster
brokerName=hannote-broker
brokerId=0
namesrvAddr=rocketmq-nameserver:9876
listenPort=10911
deleteWhen=04
fileReservedTime=24
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH
autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true
diskMaxUsedSpaceRatio=90
